sim: EF_PSRAM_CTRL_ahbl_tb.v ../../hdl/rtl/EF_PSRAM_CTRL.v ../../hdl/rtl/bus_wrapper/EF_PSRAM_CTRL_ahbl.v
	iverilog EF_PSRAM_CTRL_ahbl_tb.v ../../hdl/rtl/EF_PSRAM_CTRL.v ../../hdl/rtl/bus_wrapper/EF_PSRAM_CTRL_ahbl.v 23LC1024.v
	./a.out